from tkinter import *

window = Tk()
window.title("U.S. Senate")
lblDemocrats = Label(window, text="Democrats:")
lblRepublicans = Label(window, text="Republicans:")
lblIndependents = Label(window, text="Independents:")
entDemocrats = Entry(window, width=2, state="readonly")
entRepublicans = Entry(window, width=2, state="readonly")
entIndependents = Entry(window, width=2, state="readonly")
lblDemocrats.grid(row=1, column=1, padx=5,pady=3,sticky=E)
lblRepublicans.grid(row=2, column=1, padx=5,pady=3,sticky=E)
lblIndependents.grid(row=3, column=1, padx=5,pady=3,sticky=E)
entDemocrats.grid(row=1, column=2, pady=3, padx=5, sticky=W)
entRepublicans.grid(row=2, column=2, padx=5,pady=3,sticky=W)
entIndependents.grid(row=3, column=2, padx=5,pady=3,sticky=W)
btnDisplay = Button(text="Count Party Affiliations")
btnDisplay.grid(row=0, columnspan=4, padx=50, pady=10)
window.mainloop()
