from tkinter import *

window = Tk()
window.title("DOW")
Label(window, text="", width=1).grid(row=0, column=0)
Label(window, text="  Company:").grid(row=0, column=3,  sticky=W)
Label(window, text="  Industry:").grid(row=3, column=3, sticky=W)
Label(window, text="Exchange:").grid(row=6, column=4, sticky=E)
Label(window, text="Growth in 2013:").grid(row=7, column=4, sticky=E)
Label(window, text="Price/Earnings ratio:").grid(row=8, column=4, sticky=E)
yscroll = Scrollbar(window, orient=VERTICAL)
yscroll.grid(row=0, column=2, rowspan=9,pady=5, sticky=NS)
lstSymbols = Listbox(window, width=5, yscrollcommand=yscroll.set)
lstSymbols.grid(row=0, column=1, rowspan=9, pady=5, sticky=E)
lstSymbols.bind("<<ListboxSelect>>")
entCompany = Entry(window, state="readonly", width=30)
entCompany.grid(row=1, column=3, columnspan=2, padx=5, sticky=W)
entIndustry = Entry(window, state="readonly", width=30)
entIndustry.grid(row=4, column=3, columnspan=2, padx=5, sticky=W)
entExchange = Entry(window, width=8, state="readonly")
entExchange.grid(row=6, column=5, padx=5, sticky=W)
entGrowth = Entry(window, width=8, state="readonly")
entGrowth.grid(row=7, column=5, padx=5, sticky=W)
entPE = Entry(window, width=8, state="readonly")
entPE.grid(row=8, column=5, padx=5, sticky=W)
yscroll["command"] = lstSymbols.yview               
window.mainloop()
