COM1: {BAUDRATE: 115200, BYTESIZE: 8, FLOWCONTROL: None, PARITY: N, STOPBITS: 1.0}
COM3: {BAUDRATE: 115200, BYTESIZE: 8, FLOWCONTROL: None, PARITY: N, STOPBITS: 1.0}
COM4: {BAUDRATE: 115200, BYTESIZE: 8, FLOWCONTROL: None, PARITY: N, STOPBITS: 1.0}
COM48: {BAUDRATE: 115200, BYTESIZE: 8, FLOWCONTROL: None, PARITY: N, STOPBITS: 1.0}
COM7: {BAUDRATE: 921600, BYTESIZE: 8, FLOWCONTROL: None, PARITY: N, STOPBITS: 1.0}
COM8: {BAUDRATE: 921600, BYTESIZE: 8, FLOWCONTROL: None, PARITY: N, STOPBITS: 1.0}
COM9: {BAUDRATE: 115200, BYTESIZE: 8, FLOWCONTROL: None, PARITY: N, STOPBITS: 1.0}
COMMON: {LOGMAXSIZE: 100.0, LOGPATH: 'D:\comHub', PREFIX: DATA+TIME, TEXTMAXLINE: 100000}
LASTSESSION: COM48
